"""properties image_url

Revision ID: 5e5a1280cad4
Revises: 9adc2e6e9b1b
Create Date: 2026-05-25 09:07:36.857303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5a1280cad4'
down_revision: Union[str, Sequence[str], None] = '9adc2e6e9b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'image_url')
    # ### end Alembic commands ###
