"""initial schema

Revision ID: 7ec39dd797f7
Revises: 
Create Date: 2026-05-24 13:38:00.705384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ec39dd797f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('impower_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('PERSON', 'COMPANY', name='contact_kind'), nullable=False),
    sa.Column('salutation', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('vat_id', sa.String(), nullable=True),
    sa.Column('trade_register_number', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('mandate_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('additional_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('preferred_channel', sa.Enum('PORTAL', 'EMAIL', 'WHATSAPP', 'EPOST', name='preferred_channel'), server_default=sa.text("'EMAIL'"), nullable=False),
    sa.Column('raw_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impower_id')
    )
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('impower_id', sa.BigInteger(), nullable=True),
    sa.Column('property_hr_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OWNER', 'RENTAL', 'STRATA', name='property_type'), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'READY', 'DISABLED', name='property_state'), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('raw_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impower_id')
    )
    op.create_index('ix_properties_org_state', 'properties', ['organization_id', 'state'], unique=False)
    op.create_index(op.f('ix_properties_organization_id'), 'properties', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('sign_in_with_apple_sub', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('verwalter', 'beirat', 'eigentuemer', 'mieter', 'dienstleister', name='user_role'), nullable=False),
    sa.Column('contact_id_impower', sa.BigInteger(), nullable=True),
    sa.Column('locale', sa.String(), server_default=sa.text("'de'"), nullable=False),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_contact_id_impower'), 'users', ['contact_id_impower'], unique=False)
    op.create_index('ix_users_org_role', 'users', ['organization_id', 'role'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index('ux_users_apple_sub', 'users', ['sign_in_with_apple_sub'], unique=True, postgresql_where=sa.text('sign_in_with_apple_sub IS NOT NULL'))
    op.create_index('ux_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_index('ix_audit_log_target', 'audit_log', ['target_type', 'target_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('impower_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('raw_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impower_id')
    )
    op.create_index(op.f('ix_buildings_organization_id'), 'buildings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_buildings_property_id'), 'buildings', ['property_id'], unique=False)
    op.create_table('contact_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('bic', sa.String(), nullable=True),
    sa.Column('account_holder_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_bank_accounts_contact_id'), 'contact_bank_accounts', ['contact_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contact_id_impower', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Enum('verwalter', 'beirat', 'eigentuemer', 'mieter', 'dienstleister', name='user_role'), nullable=False),
    sa.Column('scope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_invite_codes_email'), 'invite_codes', ['email'], unique=False)
    op.create_index(op.f('ix_invite_codes_organization_id'), 'invite_codes', ['organization_id'], unique=False)
    op.create_index('ix_invite_codes_pending', 'invite_codes', ['email', 'expires_at'], unique=False, postgresql_where=sa.text('consumed_at IS NULL'))
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_hash', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('impower_id', sa.BigInteger(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('unit_hr_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('APARTMENT', 'PARKING', 'OTHER', 'COMMERCIAL', name='unit_type'), nullable=False),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('unit_rank', sa.Integer(), nullable=True),
    sa.Column('is_owned_by_weg', sa.Boolean(), nullable=True),
    sa.Column('voting_share', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rooms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('raw_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impower_id')
    )
    op.create_index(op.f('ix_units_building_id'), 'units', ['building_id'], unique=False)
    op.create_index(op.f('ix_units_organization_id'), 'units', ['organization_id'], unique=False)
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('impower_id', sa.BigInteger(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('OWNER', 'TENANT', 'PROPERTY_OWNER', name='contract_type'), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_vacant', sa.Boolean(), nullable=True),
    sa.Column('raw_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impower_id')
    )
    op.create_index('ix_contracts_org_type', 'contracts', ['organization_id', 'type'], unique=False)
    op.create_index(op.f('ix_contracts_organization_id'), 'contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contracts_property_id'), 'contracts', ['property_id'], unique=False)
    op.create_index(op.f('ix_contracts_unit_id'), 'contracts', ['unit_id'], unique=False)
    op.create_table('contract_contacts',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', 'contact_id')
    )
    op.create_index('ix_contract_contacts_contact', 'contract_contacts', ['contact_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('impower_id', sa.BigInteger(), nullable=True),
    sa.Column('sharepoint_id', sa.String(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('JAHRESABRECHNUNG', 'WIRTSCHAFTSPLAN', 'PROTOKOLL', 'VERTRAG', 'RECHNUNG', 'UMLAUFBESCHLUSS', 'HAUSORDNUNG', 'SONSTIGES', name='document_kind'), server_default=sa.text("'SONSTIGES'"), nullable=False),
    sa.Column('impower_source_type', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_url', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'BEIRAT_ONLY', 'OWNERS', 'TENANTS', 'ALL', name='document_visibility'), server_default=sa.text("'PRIVATE'"), nullable=False),
    sa.Column('state', sa.Enum('PENDING_REVIEW', 'DRAFT', 'GENERATING', 'READY', 'FAILED', 'DELETED', name='document_state'), nullable=True),
    sa.Column('raw_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('impower_id')
    )
    op.create_index(op.f('ix_documents_building_id'), 'documents', ['building_id'], unique=False)
    op.create_index(op.f('ix_documents_contact_id'), 'documents', ['contact_id'], unique=False)
    op.create_index(op.f('ix_documents_contract_id'), 'documents', ['contract_id'], unique=False)
    op.create_index('ix_documents_org_kind', 'documents', ['organization_id', 'kind'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_property_id'), 'documents', ['property_id'], unique=False)
    op.create_index(op.f('ix_documents_unit_id'), 'documents', ['unit_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the single WHV organization (ADR-0002: single-tenant deployment,
    # multi-tenant-ready schemas). UUID is fixed so every environment shares it.
    op.execute(
        """
        INSERT INTO organizations (id, name, created_at, updated_at)
        VALUES (
            '01958d20-0000-7000-8000-000000005748',
            'Wagner Hausverwaltung GmbH',
            NOW(),
            NOW()
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_unit_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_property_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_documents_org_kind', table_name='documents')
    op.drop_index(op.f('ix_documents_contract_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_contact_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_building_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_contract_contacts_contact', table_name='contract_contacts')
    op.drop_table('contract_contacts')
    op.drop_index(op.f('ix_contracts_unit_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_property_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_organization_id'), table_name='contracts')
    op.drop_index('ix_contracts_org_type', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    op.drop_index(op.f('ix_units_organization_id'), table_name='units')
    op.drop_index(op.f('ix_units_building_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_invite_codes_pending', table_name='invite_codes', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_index(op.f('ix_invite_codes_organization_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_email'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_contact_bank_accounts_contact_id'), table_name='contact_bank_accounts')
    op.drop_table('contact_bank_accounts')
    op.drop_index(op.f('ix_buildings_property_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_organization_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('ix_audit_log_target', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ux_users_email_lower', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ux_users_apple_sub', table_name='users', postgresql_where=sa.text('sign_in_with_apple_sub IS NOT NULL'))
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_org_role', table_name='users')
    op.drop_index(op.f('ix_users_contact_id_impower'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_organization_id'), table_name='properties')
    op.drop_index('ix_properties_org_state', table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # Drop named PostgreSQL enum types created inline with the tables above.
    # Autogenerate does not emit these.
    for type_name in (
        "contact_kind",
        "preferred_channel",
        "contract_type",
        "document_kind",
        "document_state",
        "document_visibility",
        "property_state",
        "property_type",
        "unit_type",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
