"""circular_resolutions_and_votes

Revision ID: a46a5d5b5449
Revises: c1a4e8d9b201
Create Date: 2026-05-24 21:44:35.247027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a46a5d5b5449'
down_revision: Union[str, Sequence[str], None] = 'c1a4e8d9b201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circular_resolutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mode', sa.Enum('KLASSISCH', 'MEHRHEITS', name='resolution_mode'), nullable=False),
    sa.Column('status', sa.Enum('ENTWURF', 'OFFEN', 'GESCHLOSSEN', 'ANGENOMMEN', 'ABGELEHNT', name='resolution_status'), server_default='ENTWURF', nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('required_quorum', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('result_pdf_url', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opens_on', sa.Date(), nullable=True),
    sa.Column('closes_on', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circular_resolutions_created_by'), 'circular_resolutions', ['created_by'], unique=False)
    op.create_index('ix_circular_resolutions_org_status', 'circular_resolutions', ['organization_id', 'status', 'closes_at'], unique=False)
    op.create_index(op.f('ix_circular_resolutions_organization_id'), 'circular_resolutions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_circular_resolutions_property_id'), 'circular_resolutions', ['property_id'], unique=False)
    op.create_index('ix_circular_resolutions_property_status', 'circular_resolutions', ['property_id', 'status'], unique=False)
    op.create_table('circular_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resolution_id', sa.UUID(), nullable=False),
    sa.Column('owner_contact_id_impower', sa.BigInteger(), nullable=False),
    sa.Column('choice', sa.Enum('JA', 'NEIN', 'ENTHALTUNG', name='vote_choice'), nullable=False),
    sa.Column('voter_user_id', sa.UUID(), nullable=True),
    sa.Column('signature_method', sa.Text(), server_default='PORTAL_CLICK', nullable=False),
    sa.Column('evidence_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolution_id'], ['circular_resolutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resolution_id', 'owner_contact_id_impower', name='uq_circular_votes_resolution_owner')
    )
    op.create_index('ix_circular_votes_resolution', 'circular_votes', ['resolution_id', 'voted_at'], unique=False)
    op.create_index(op.f('ix_circular_votes_resolution_id'), 'circular_votes', ['resolution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circular_votes_resolution_id'), table_name='circular_votes')
    op.drop_index('ix_circular_votes_resolution', table_name='circular_votes')
    op.drop_table('circular_votes')
    op.drop_index('ix_circular_resolutions_property_status', table_name='circular_resolutions')
    op.drop_index(op.f('ix_circular_resolutions_property_id'), table_name='circular_resolutions')
    op.drop_index(op.f('ix_circular_resolutions_organization_id'), table_name='circular_resolutions')
    op.drop_index('ix_circular_resolutions_org_status', table_name='circular_resolutions')
    op.drop_index(op.f('ix_circular_resolutions_created_by'), table_name='circular_resolutions')
    op.drop_table('circular_resolutions')
    # ### end Alembic commands ###
