"""tickets

Revision ID: dc5ce209aa42
Revises: fc97cf1c47f3
Create Date: 2026-05-24 18:46:00.707924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5ce209aa42'
down_revision: Union[str, Sequence[str], None] = 'fc97cf1c47f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('SCHADEN', 'VERWALTUNG', 'HAUSGELD', 'SONSTIGES', name='ticket_category'), nullable=False),
    sa.Column('status', sa.Enum('NEU', 'OFFEN', 'WARTET_AUF_KUNDE', 'GESCHLOSSEN', name='ticket_status'), server_default='NEU', nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assignee_user_id'), 'tickets', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_by_user_id'), 'tickets', ['created_by_user_id'], unique=False)
    op.create_index('ix_tickets_creator_status', 'tickets', ['created_by_user_id', 'status'], unique=False)
    op.create_index('ix_tickets_org_status_last_msg', 'tickets', ['organization_id', 'status', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_tickets_organization_id'), 'tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tickets_property_id'), 'tickets', ['property_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_author_user_id'), 'ticket_messages', ['author_user_id'], unique=False)
    op.create_index('ix_ticket_messages_thread', 'ticket_messages', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index('ix_ticket_messages_thread', table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_author_user_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_tickets_property_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_organization_id'), table_name='tickets')
    op.drop_index('ix_tickets_org_status_last_msg', table_name='tickets')
    op.drop_index('ix_tickets_creator_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_by_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_user_id'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
