"""ticket_participants_and_share_scope

Revision ID: fbf593d062e7
Revises: dc5ce209aa42
Create Date: 2026-05-24 19:05:59.989386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf593d062e7'
down_revision: Union[str, Sequence[str], None] = 'dc5ce209aa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogen did NOT emit a CREATE TYPE for the new enum before using it on
    # the ALTER TABLE; create it explicitly first so the ADD COLUMN succeeds.
    share_scope_enum = sa.Enum(
        "PRIVATE", "PARTICIPANTS", "PROPERTY", name="ticket_share_scope"
    )
    share_scope_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "ticket_participants",
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("added_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["added_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ticket_id", "user_id"),
    )
    op.create_index(
        op.f("ix_ticket_participants_added_by_user_id"),
        "ticket_participants",
        ["added_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_ticket_participants_user", "ticket_participants", ["user_id"], unique=False
    )
    op.add_column(
        "tickets",
        sa.Column(
            "share_scope",
            share_scope_enum,
            server_default="PRIVATE",
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'share_scope')
    op.drop_index('ix_ticket_participants_user', table_name='ticket_participants')
    op.drop_index(op.f('ix_ticket_participants_added_by_user_id'), table_name='ticket_participants')
    op.drop_table('ticket_participants')
    # ### end Alembic commands ###
