"""SQLAlchemy models for the RAG vector store (ADR-0013).

These tables live in a SEPARATE Postgres database (the `vectordb`
pgvector container), NOT the app DB — so they use their own declarative
``RagBase`` and are never swept into the app's Alembic autogenerate. The
store is a DERIVED, rebuildable cache: every row can be regenerated by
re-ingesting from Impower, so it's provisioned by
``app.rag.db.init_rag_store`` (CREATE EXTENSION + create_all), not the
app's immutable-migration discipline.

The UUID columns (``organization_id``, ``property_id`` …) mirror the app
DB's ids but carry NO cross-database foreign keys (impossible across
databases) — they are the §2 ACL *scope tags* applied as a metadata
WHERE-filter BEFORE the vector similarity search.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from decimal import Decimal

from pgvector.sqlalchemy import Vector
from sqlalchemy import Date, DateTime, Index, Integer, Numeric, String, Text, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.rag.constants import EMBEDDING_DIM


class RagBase(DeclarativeBase):
    """Declarative base for the RAG store — intentionally separate from
    the app's ``app.db.Base`` so app-side migrations never see these."""


class RagDocument(RagBase):
    """One row per indexed source ``Document`` (1:1 on the app id).

    Holds the OCR'd text + the *authoritative* structured metadata copied
    from Impower (amount / issued_date / contact). Per ADR-0013 §3 numbers
    + dates come from Impower's structured fields, never from OCR.
    """

    __tablename__ = "rag_documents"

    # The app-side Document.id (UUIDv7). PK because indexing is 1:1.
    document_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    # Extracted content + provenance.
    extracted_text: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    ocr_engine: Mapped[str] = mapped_column(String(40), nullable=False)
    page_count: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Linked structured metadata (authoritative — from Impower, not OCR).
    source_kind: Mapped[str | None] = mapped_column(String(80), nullable=True)
    amount: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    issued_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    contact_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    contact_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    property_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    unit_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)

    # ACL scope (mirrors the §2 columns; the chunk rows carry these too).
    visibility: Mapped[str] = mapped_column(String(40), nullable=False)
    sensitivity: Mapped[str] = mapped_column(
        String(20), nullable=False, default="normal", server_default=text("'normal'")
    )

    indexed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class RagChunk(RagBase):
    """A retrievable chunk: text + embedding + the §2 ACL scope tags +
    the copied-down filterable metadata used by hybrid retrieval."""

    __tablename__ = "rag_chunks"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )

    # --- §2 ACL scope columns — the hard pre-filter applied BEFORE ANN ---
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    property_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    unit_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    contract_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    contact_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    visibility: Mapped[str] = mapped_column(String(40), nullable=False)
    source_type: Mapped[str] = mapped_column(
        String(20), nullable=False, default="document", server_default=text("'document'")
    )
    sensitivity: Mapped[str] = mapped_column(
        String(20), nullable=False, default="normal", server_default=text("'normal'")
    )

    # --- content ---
    chunk_text: Mapped[str] = mapped_column(Text, nullable=False)
    page: Mapped[int | None] = mapped_column(Integer, nullable=True)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)

    # --- copied-down filterable metadata (the structured half of hybrid
    # retrieval; numbers come from Impower, never OCR — ADR-0013 §3) ---
    source_kind: Mapped[str | None] = mapped_column(String(80), nullable=True)
    amount: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    issued_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    issued_year: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)
    contact_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


# Composite index for the ACL pre-filter — (org, property) is the hottest
# scoping path for non-VERWALTER callers.
Index("ix_rag_chunks_scope", RagChunk.organization_id, RagChunk.property_id)

# HNSW ANN index for cosine similarity. Built on an empty table at
# bootstrap; pgvector backfills as rows are inserted. cosine because the
# embeddings are normalised — distance = 1 - cosine_similarity.
Index(
    "ix_rag_chunks_embedding_hnsw",
    RagChunk.embedding,
    postgresql_using="hnsw",
    postgresql_with={"m": 16, "ef_construction": 64},
    postgresql_ops={"embedding": "vector_cosine_ops"},
)
